### ISSUE TITLE
Parallax images not working on firefox

### ISSUE THREAD

**Issue by benmarley** [benmarley/portfolio#16]
Hey Thomas
I did a cool/weird little triptych parallax in a grid that i'll be replacing with graphics, but its not working on firefox or safari but works perfect in chrome. any idea why?

Thanks
Ben

@thomasjbradley

**Comment by thomasjbradley** [comment]
It could be where the `.parallax` class is, it should be surrounding _all_ the parallaxing items, not just each item individually.

**Comment by benmarley** [comment]
So I tried that, and I even got rid of the other two for now, and I made it really simple. its now working in safari, but it still isn't working in firefox.

**Comment by thomasjbradley** [comment]
I've got a solution, but will require some changes to the HTML: if `.parallax-group` is outside `<main>`, directly inside `<body>` it works.
